# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Encodex_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Encodex(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(771, 493)
        MainWindow.setMinimumSize(QtCore.QSize(771, 493))
        MainWindow.setMaximumSize(QtCore.QSize(771, 493))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_input = QtWidgets.QLabel(self.centralwidget)
        self.label_input.setGeometry(QtCore.QRect(10, 10, 741, 71))
        self.label_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_input.setText("")
        self.label_input.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_input.setObjectName("label_input")
        self.pushButton_A = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_A.setGeometry(QtCore.QRect(10, 104, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_A.sizePolicy().hasHeightForWidth())
        self.pushButton_A.setSizePolicy(sizePolicy)
        self.pushButton_A.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_A.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_A.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_A.setObjectName("pushButton_A")
        self.pushButton_G = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_G.setGeometry(QtCore.QRect(10, 163, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_G.sizePolicy().hasHeightForWidth())
        self.pushButton_G.setSizePolicy(sizePolicy)
        self.pushButton_G.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_G.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_G.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_G.setObjectName("pushButton_G")
        self.pushButton_B = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_B.setGeometry(QtCore.QRect(79, 104, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_B.sizePolicy().hasHeightForWidth())
        self.pushButton_B.setSizePolicy(sizePolicy)
        self.pushButton_B.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_B.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_B.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_B.setObjectName("pushButton_B")
        self.pushButton_H = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_H.setGeometry(QtCore.QRect(79, 163, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_H.sizePolicy().hasHeightForWidth())
        self.pushButton_H.setSizePolicy(sizePolicy)
        self.pushButton_H.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_H.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_H.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_H.setObjectName("pushButton_H")
        self.pushButton_C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_C.setGeometry(QtCore.QRect(148, 104, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_C.sizePolicy().hasHeightForWidth())
        self.pushButton_C.setSizePolicy(sizePolicy)
        self.pushButton_C.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_C.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_C.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_C.setObjectName("pushButton_C")
        self.pushButton_D = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_D.setGeometry(QtCore.QRect(217, 104, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_D.sizePolicy().hasHeightForWidth())
        self.pushButton_D.setSizePolicy(sizePolicy)
        self.pushButton_D.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_D.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_D.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_D.setObjectName("pushButton_D")
        self.pushButton_E = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_E.setGeometry(QtCore.QRect(286, 104, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_E.sizePolicy().hasHeightForWidth())
        self.pushButton_E.setSizePolicy(sizePolicy)
        self.pushButton_E.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_E.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_E.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_E.setObjectName("pushButton_E")
        self.pushButton_F = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_F.setGeometry(QtCore.QRect(355, 104, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_F.sizePolicy().hasHeightForWidth())
        self.pushButton_F.setSizePolicy(sizePolicy)
        self.pushButton_F.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_F.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_F.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_F.setObjectName("pushButton_F")
        self.pushButton_N = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_N.setGeometry(QtCore.QRect(79, 222, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_N.sizePolicy().hasHeightForWidth())
        self.pushButton_N.setSizePolicy(sizePolicy)
        self.pushButton_N.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_N.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_N.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_N.setObjectName("pushButton_N")
        self.pushButton_M = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_M.setGeometry(QtCore.QRect(10, 222, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_M.sizePolicy().hasHeightForWidth())
        self.pushButton_M.setSizePolicy(sizePolicy)
        self.pushButton_M.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_M.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_M.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_M.setObjectName("pushButton_M")
        self.pushButton_P = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_P.setGeometry(QtCore.QRect(217, 222, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_P.sizePolicy().hasHeightForWidth())
        self.pushButton_P.setSizePolicy(sizePolicy)
        self.pushButton_P.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_P.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_P.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_P.setObjectName("pushButton_P")
        self.pushButton_R = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_R.setGeometry(QtCore.QRect(355, 222, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_R.sizePolicy().hasHeightForWidth())
        self.pushButton_R.setSizePolicy(sizePolicy)
        self.pushButton_R.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_R.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_R.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_R.setObjectName("pushButton_R")
        self.pushButton_Q = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Q.setGeometry(QtCore.QRect(286, 222, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Q.sizePolicy().hasHeightForWidth())
        self.pushButton_Q.setSizePolicy(sizePolicy)
        self.pushButton_Q.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_Q.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_Q.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_Q.setObjectName("pushButton_Q")
        self.pushButton_O = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_O.setGeometry(QtCore.QRect(148, 222, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_O.sizePolicy().hasHeightForWidth())
        self.pushButton_O.setSizePolicy(sizePolicy)
        self.pushButton_O.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_O.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_O.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_O.setObjectName("pushButton_O")
        self.pushButton_K = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_K.setGeometry(QtCore.QRect(286, 163, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_K.sizePolicy().hasHeightForWidth())
        self.pushButton_K.setSizePolicy(sizePolicy)
        self.pushButton_K.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_K.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_K.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_K.setObjectName("pushButton_K")
        self.pushButton_J = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_J.setGeometry(QtCore.QRect(217, 163, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_J.sizePolicy().hasHeightForWidth())
        self.pushButton_J.setSizePolicy(sizePolicy)
        self.pushButton_J.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_J.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_J.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_J.setObjectName("pushButton_J")
        self.pushButton_I = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_I.setGeometry(QtCore.QRect(148, 163, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_I.sizePolicy().hasHeightForWidth())
        self.pushButton_I.setSizePolicy(sizePolicy)
        self.pushButton_I.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_I.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_I.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_I.setObjectName("pushButton_I")
        self.pushButton_L = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_L.setGeometry(QtCore.QRect(355, 163, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_L.sizePolicy().hasHeightForWidth())
        self.pushButton_L.setSizePolicy(sizePolicy)
        self.pushButton_L.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_L.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_L.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_L.setObjectName("pushButton_L")
        self.pushButton_W = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_W.setGeometry(QtCore.QRect(286, 281, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_W.sizePolicy().hasHeightForWidth())
        self.pushButton_W.setSizePolicy(sizePolicy)
        self.pushButton_W.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_W.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_W.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_W.setObjectName("pushButton_W")
        self.pushButton_V = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_V.setGeometry(QtCore.QRect(217, 281, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_V.sizePolicy().hasHeightForWidth())
        self.pushButton_V.setSizePolicy(sizePolicy)
        self.pushButton_V.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_V.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_V.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_V.setObjectName("pushButton_V")
        self.pushButton_T = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_T.setGeometry(QtCore.QRect(79, 281, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_T.sizePolicy().hasHeightForWidth())
        self.pushButton_T.setSizePolicy(sizePolicy)
        self.pushButton_T.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_T.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_T.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_T.setObjectName("pushButton_T")
        self.pushButton_U = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_U.setGeometry(QtCore.QRect(148, 281, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_U.sizePolicy().hasHeightForWidth())
        self.pushButton_U.setSizePolicy(sizePolicy)
        self.pushButton_U.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_U.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_U.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_U.setObjectName("pushButton_U")
        self.pushButton_S = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_S.setGeometry(QtCore.QRect(10, 281, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_S.sizePolicy().hasHeightForWidth())
        self.pushButton_S.setSizePolicy(sizePolicy)
        self.pushButton_S.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_S.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_S.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_S.setObjectName("pushButton_S")
        self.pushButton_X = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_X.setGeometry(QtCore.QRect(355, 281, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_X.sizePolicy().hasHeightForWidth())
        self.pushButton_X.setSizePolicy(sizePolicy)
        self.pushButton_X.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_X.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_X.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_X.setObjectName("pushButton_X")
        self.pushButton_Y = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Y.setGeometry(QtCore.QRect(10, 340, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Y.sizePolicy().hasHeightForWidth())
        self.pushButton_Y.setSizePolicy(sizePolicy)
        self.pushButton_Y.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_Y.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_Y.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_Y.setObjectName("pushButton_Y")
        self.pushButton_Z = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Z.setGeometry(QtCore.QRect(355, 340, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Z.sizePolicy().hasHeightForWidth())
        self.pushButton_Z.setSizePolicy(sizePolicy)
        self.pushButton_Z.setMinimumSize(QtCore.QSize(71, 61))
        self.pushButton_Z.setMaximumSize(QtCore.QSize(71, 61))
        self.pushButton_Z.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_Z.setObjectName("pushButton_Z")
        self.pushButton_shift = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_shift.setGeometry(QtCore.QRect(79, 340, 140, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_shift.sizePolicy().hasHeightForWidth())
        self.pushButton_shift.setSizePolicy(sizePolicy)
        self.pushButton_shift.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_shift.setMaximumSize(QtCore.QSize(8000, 200))
        self.pushButton_shift.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.pushButton_shift.setObjectName("pushButton_shift")
        self.pushButton_n1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_n1.setGeometry(QtCore.QRect(442, 105, 51, 41))
        self.pushButton_n1.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_n1.setObjectName("pushButton_n1")
        self.pushButton_n2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_n2.setGeometry(QtCore.QRect(491, 105, 51, 41))
        self.pushButton_n2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_n2.setObjectName("pushButton_n2")
        self.pushButton_n3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_n3.setGeometry(QtCore.QRect(540, 105, 51, 41))
        self.pushButton_n3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_n3.setObjectName("pushButton_n3")
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(10, 420, 751, 41))
        self.label_output.setStyleSheet("background-color: rgb(243, 243, 232);")
        self.label_output.setText("")
        self.label_output.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_output.setObjectName("label_output")
        self.pushButton_n5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_n5.setGeometry(QtCore.QRect(491, 144, 51, 41))
        self.pushButton_n5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_n5.setObjectName("pushButton_n5")
        self.pushButton_n6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_n6.setGeometry(QtCore.QRect(540, 144, 51, 41))
        self.pushButton_n6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_n6.setObjectName("pushButton_n6")
        self.pushButton_n4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_n4.setGeometry(QtCore.QRect(442, 144, 51, 41))
        self.pushButton_n4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_n4.setObjectName("pushButton_n4")
        self.pushButton_n7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_n7.setGeometry(QtCore.QRect(442, 183, 51, 41))
        self.pushButton_n7.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_n7.setObjectName("pushButton_n7")
        self.pushButton_n8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_n8.setGeometry(QtCore.QRect(491, 183, 51, 41))
        self.pushButton_n8.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_n8.setObjectName("pushButton_n8")
        self.pushButton_n9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_n9.setGeometry(QtCore.QRect(540, 183, 51, 41))
        self.pushButton_n9.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_n9.setObjectName("pushButton_n9")
        self.pushButton_plus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plus.setGeometry(QtCore.QRect(540, 222, 51, 41))
        self.pushButton_plus.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.pushButton_dot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dot.setGeometry(QtCore.QRect(491, 222, 51, 41))
        self.pushButton_dot.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.pushButton_n0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_n0.setGeometry(QtCore.QRect(442, 222, 51, 41))
        self.pushButton_n0.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_n0.setObjectName("pushButton_n0")
        self.pushButton_minus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_minus.setGeometry(QtCore.QRect(442, 261, 51, 41))
        self.pushButton_minus.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_star = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_star.setGeometry(QtCore.QRect(491, 261, 51, 41))
        self.pushButton_star.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_star.setObjectName("pushButton_star")
        self.pushButton_slash = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_slash.setGeometry(QtCore.QRect(540, 261, 51, 41))
        self.pushButton_slash.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_slash.setObjectName("pushButton_slash")
        self.pushButton_excalim = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_excalim.setGeometry(QtCore.QRect(540, 300, 51, 41))
        self.pushButton_excalim.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_excalim.setObjectName("pushButton_excalim")
        self.pushButton_comma = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_comma.setGeometry(QtCore.QRect(442, 300, 51, 41))
        self.pushButton_comma.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.pushButton_comma.setObjectName("pushButton_comma")
        self.pushButton_quote = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quote.setGeometry(QtCore.QRect(491, 300, 51, 41))
        self.pushButton_quote.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_quote.setObjectName("pushButton_quote")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 83, 751, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_backSpace = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_backSpace.setGeometry(QtCore.QRect(620, 260, 131, 41))
        self.pushButton_backSpace.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.pushButton_backSpace.setObjectName("pushButton_backSpace")
        self.pushButton_ascii = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ascii.setGeometry(QtCore.QRect(620, 105, 131, 41))
        self.pushButton_ascii.setStyleSheet("background-color: rgb(221, 221, 221);\n"
"")
        self.pushButton_ascii.setObjectName("pushButton_ascii")
        self.pushButton_binary = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_binary.setGeometry(QtCore.QRect(620, 153, 131, 41))
        self.pushButton_binary.setStyleSheet("background-color: rgb(221, 221, 221);\n"
"")
        self.pushButton_binary.setObjectName("pushButton_binary")
        self.pushButton_hex = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_hex.setGeometry(QtCore.QRect(620, 200, 131, 41))
        self.pushButton_hex.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.pushButton_hex.setObjectName("pushButton_hex")
        self.pushButton_copyValue = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_copyValue.setGeometry(QtCore.QRect(620, 310, 61, 31))
        self.pushButton_copyValue.setStyleSheet("background-color: rgb(88, 176, 0);\n"
"font: 7pt \"MS Shell Dlg 2\";")
        self.pushButton_copyValue.setObjectName("pushButton_copyValue")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(426, 106, 16, 291))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(596, 106, 16, 291))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 402, 751, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(616, 240, 141, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pushButton_pound = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pound.setGeometry(QtCore.QRect(442, 339, 51, 41))
        self.pushButton_pound.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.pushButton_pound.setObjectName("pushButton_pound")
        self.pushButton_at = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_at.setGeometry(QtCore.QRect(491, 339, 51, 41))
        self.pushButton_at.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.pushButton_at.setObjectName("pushButton_at")
        self.pushButton_dolar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dolar.setGeometry(QtCore.QRect(540, 339, 51, 41))
        self.pushButton_dolar.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.pushButton_dolar.setObjectName("pushButton_dolar")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(620, 350, 131, 41))
        self.pushButton_clear.setStyleSheet("background-color: rgb(221, 221, 221);\n"
"color: rgb(85, 170, 0);\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_space = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_space.setGeometry(QtCore.QRect(217, 340, 140, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_space.sizePolicy().hasHeightForWidth())
        self.pushButton_space.setSizePolicy(sizePolicy)
        self.pushButton_space.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_space.setMaximumSize(QtCore.QSize(8000, 200))
        self.pushButton_space.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.pushButton_space.setObjectName("pushButton_space")
        self.label_message = QtWidgets.QLabel(self.centralwidget)
        self.label_message.setGeometry(QtCore.QRect(13, 420, 291, 16))
        self.label_message.setStyleSheet("font: italic 8pt \"Kokila\";\n"
"font: italic 8pt \"Arial\";")
        self.label_message.setObjectName("label_message")
        self.pushButton_use_as_input = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_use_as_input.setGeometry(QtCore.QRect(690, 310, 61, 31))
        self.pushButton_use_as_input.setStyleSheet("font: 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(179, 220, 255);")
        self.pushButton_use_as_input.setObjectName("pushButton_use_as_input")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 771, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit_Application = QtWidgets.QAction(MainWindow)
        self.actionExit_Application.setObjectName("actionExit_Application")
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionExit_Application)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit_Application.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Encodex"))
        self.pushButton_A.setText(_translate("MainWindow", "A"))
        self.pushButton_G.setText(_translate("MainWindow", "G"))
        self.pushButton_B.setText(_translate("MainWindow", "B"))
        self.pushButton_H.setText(_translate("MainWindow", "H"))
        self.pushButton_C.setText(_translate("MainWindow", "C"))
        self.pushButton_D.setText(_translate("MainWindow", "D"))
        self.pushButton_E.setText(_translate("MainWindow", "E"))
        self.pushButton_F.setText(_translate("MainWindow", "F"))
        self.pushButton_N.setText(_translate("MainWindow", "N"))
        self.pushButton_M.setText(_translate("MainWindow", "M"))
        self.pushButton_P.setText(_translate("MainWindow", "P"))
        self.pushButton_R.setText(_translate("MainWindow", "R"))
        self.pushButton_Q.setText(_translate("MainWindow", "Q"))
        self.pushButton_O.setText(_translate("MainWindow", "O"))
        self.pushButton_K.setText(_translate("MainWindow", "K"))
        self.pushButton_J.setText(_translate("MainWindow", "J"))
        self.pushButton_I.setText(_translate("MainWindow", "I"))
        self.pushButton_L.setText(_translate("MainWindow", "L"))
        self.pushButton_W.setText(_translate("MainWindow", "W"))
        self.pushButton_V.setText(_translate("MainWindow", "V"))
        self.pushButton_T.setText(_translate("MainWindow", "T"))
        self.pushButton_U.setText(_translate("MainWindow", "U"))
        self.pushButton_S.setText(_translate("MainWindow", "S"))
        self.pushButton_X.setText(_translate("MainWindow", "X"))
        self.pushButton_Y.setText(_translate("MainWindow", "Y"))
        self.pushButton_Z.setText(_translate("MainWindow", "Z"))
        self.pushButton_shift.setText(_translate("MainWindow", "SHIFT"))
        self.pushButton_n1.setText(_translate("MainWindow", "1"))
        self.pushButton_n2.setText(_translate("MainWindow", "2"))
        self.pushButton_n3.setText(_translate("MainWindow", "3"))
        self.pushButton_n5.setText(_translate("MainWindow", "5"))
        self.pushButton_n6.setText(_translate("MainWindow", "6"))
        self.pushButton_n4.setText(_translate("MainWindow", "4"))
        self.pushButton_n7.setText(_translate("MainWindow", "7"))
        self.pushButton_n8.setText(_translate("MainWindow", "8"))
        self.pushButton_n9.setText(_translate("MainWindow", "9"))
        self.pushButton_plus.setText(_translate("MainWindow", "+"))
        self.pushButton_dot.setText(_translate("MainWindow", "."))
        self.pushButton_n0.setText(_translate("MainWindow", "0"))
        self.pushButton_minus.setText(_translate("MainWindow", "-"))
        self.pushButton_star.setText(_translate("MainWindow", "*"))
        self.pushButton_slash.setText(_translate("MainWindow", "/"))
        self.pushButton_excalim.setText(_translate("MainWindow", "!"))
        self.pushButton_comma.setText(_translate("MainWindow", ","))
        self.pushButton_quote.setText(_translate("MainWindow", "\""))
        self.pushButton_backSpace.setText(_translate("MainWindow", "Back Space"))
        self.pushButton_ascii.setText(_translate("MainWindow", "Get ASCII value"))
        self.pushButton_binary.setText(_translate("MainWindow", "Get Binary Value"))
        self.pushButton_hex.setText(_translate("MainWindow", "Get Hex Value"))
        self.pushButton_copyValue.setText(_translate("MainWindow", "Copy Value"))
        self.pushButton_pound.setText(_translate("MainWindow", "#"))
        self.pushButton_at.setText(_translate("MainWindow", "@"))
        self.pushButton_dolar.setText(_translate("MainWindow", "$"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_space.setText(_translate("MainWindow", "Space"))
        self.label_message.setText(_translate("MainWindow", "Output~"))
        self.pushButton_use_as_input.setText(_translate("MainWindow", "Use as input"))
        self.menuAbout.setTitle(_translate("MainWindow", "Menu"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExit_Application.setText(_translate("MainWindow", "Exit Application"))
